image: node:12.18.2

cache:
  key: event_web
  paths:
    - .npm/

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  STAGING_CDN_DISTRIBUTION_ID: E1PN7CUQQZ69AV
  PROD_CDN_DISTRIBUTION_ID: EOHRS0Q0OCXKQ
  TEST_CDN_DISTRIBUTION_ID: EM6D9VOGZ87XQ
  CHROMATIC_PROJECT_TOKEN: 23ddd4a789c0

stages:
  - setup
  - tests
  - build
  - deploy

install_packages:
  stage: setup
  except:
    refs:
      - staging
      - production
      - test
  script:
    - npm i --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/

check_format:
  stage: tests
  except:
    refs:
      - staging
      - production
      - test
  script:
    - npm run check-format

check_types:
  stage: tests
  except:
    refs:
      - staging
      - production
      - test
  script:
    - npm run check-types

jest:
  stage: tests
  except:
    refs:
      - staging
      - production
      - test
  artifacts:
    paths:
      - coverage
  script:
    - npm run test:coverage
  retry: 2

publish_storybook:
  stage: tests
  only:
    refs:
      - develop
  script:
    - npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes

build_test:
  stage: build
  only:
    refs:
      - test
  script:
    - npm i --cache .npm --prefer-offline
    - npm run build
  variables:
    REACT_APP_API_URL: 'https://v1-test.obv.io'
    REACT_APP_WEB_APP_ROOT: 'test.obv.io'
    REACT_APP_IS_STAGING: 'true'
    REACT_APP_CK_EDITOR_UPLOAD_URL: 'https://80003.cke-cs.com/easyimage/upload/'
  artifacts:
    paths:
      - build/

deploy_test:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  only:
    refs:
      - test
  script:
    - aws s3 sync build/ s3://obvio-event-web-test
    - aws cloudfront create-invalidation --distribution-id
      $TEST_CDN_DISTRIBUTION_ID --paths "/*"

build_staging:
  stage: build
  only:
    refs:
      - staging
  script:
    - npm i --cache .npm --prefer-offline
    - npm run build
  variables:
    REACT_APP_API_URL: 'https://v1-staging.obv.io'
    REACT_APP_WEB_APP_ROOT: 'staging.obv.io'
    REACT_APP_IS_STAGING: 'true'
    REACT_APP_CK_EDITOR_UPLOAD_URL: 'https://80003.cke-cs.com/easyimage/upload/'
    REACT_APP_PUSHER_KEY: $PUSHER_APP_STAGING_KEY
    REACT_APP_STRIPE_PK: $STRIPE_PK_STAGING
  artifacts:
    paths:
      - build/

deploy_staging:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  only:
    refs:
      - staging
  script:
    - aws s3 sync build/ s3://obvio-event-web-staging
    - aws cloudfront create-invalidation --distribution-id
      $STAGING_CDN_DISTRIBUTION_ID --paths "/*"

build_prod:
  stage: build
  only:
    refs:
      - production
  script:
    - npm i --cache .npm --prefer-offline
    - npm run build
  variables:
    REACT_APP_EVENT_API_URL: https://v1-cdn.obv.io
    REACT_APP_ADMIN_API_URL: 'https://v1-admin.obv.io'
    REACT_APP_WEB_APP_ROOT: 'obv.io'
    REACT_APP_CK_EDITOR_UPLOAD_URL: 'https://80003.cke-cs.com/easyimage/upload/'
    REACT_APP_PUSHER_KEY: $PUSHER_APP_PRODUCTION_KEY
    REACT_APP_STRIPE_PK: $STRIPE_PK_PRODUCTION
  artifacts:
    paths:
      - build/

deploy_prod:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  only:
    refs:
      - production
  script:
    - aws s3 sync build/ s3://obvio-event-web
    - aws cloudfront create-invalidation --distribution-id
      $PROD_CDN_DISTRIBUTION_ID --paths "/*"

