image: node:12.18.2

cache:
  key: event_web
  paths:
    - .npm/

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - test
  - build
  - deploy

unit_tests:
  stage: test
  except:
    refs:
      - staging
      - production
  script:
    - npm i --cache .npm --prefer-offline
    - npm test

build:
  stage: build
  only:
    refs:
      - staging
      - production
  script:
    - npm i --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - build/

deploy_staging:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  only:
    refs:
      - staging
  script:
    - aws s3 sync build/ s3://obvio-event-web-staging
